export const AUTH_USER = "AUTH_USER";
export const UNAUTH_USER = "UNAUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const FETCH_MESSAGE = "FETCH_MESSAGE";

export const FETCH_GET_PRODUCTS = "FETCH_GET_PRODUCTS";
export const FETCH_GET_PRODUCTS_ERROR = "FETCH_GET_PRODUCTS_ERROR";
export const FETCH_GET_PRODUCTS_SUCCESS = "FETCH_GET_PRODUCTS_SUCCESS";

export const FETCH_GET_USER_PLACES = "FETCH_GET_USER_PLACES";
export const FETCH_GET_USER_PLACES_SUCCESS = "FETCH_GET_USER_PLACES_SUCCESS";
export const FETCH_GET_USER_PLACES_ERROR = "FETCH_GET_USER_PLACES_ERROR";

export const SET_USER_INFO = "SET_USER_INFO";

export const GET_ALL_RATES_SUCCESS = "GET_ALL_RATES_SUCCESS";
export const GET_ALL_RATES_FAILED = "GET_ALL_RATES_FAILED";
